api_platform:
    title: Gym Manager
    version: 1.0.0
    mapping:
        paths: [
                '%kernel.project_dir%/src/Infrastructure/User/Entity',
                '%kernel.project_dir%/src/UI/User/Http/Dto'
        ]
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    defaults:
        stateless: true
        # Good cache defaults
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
