doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            gender_type: App\Infrastructure\Shared\Type\GenderType
            offer_type: App\Infrastructure\Offer\Type\OfferType
            offer_status: App\Infrastructure\Offer\Type\OfferStatusType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Infrastructure/User/Entity'
                prefix: 'App\Infrastructure\User\Entity'
                alias: User
            Client:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Infrastructure/Client/Entity'
                prefix: 'App\Infrastructure\Client\Entity'
                alias: Client
            Offer:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Infrastructure/Offer/Entity'
                prefix: 'App\Infrastructure\Offer\Entity'
                alias: Offer
